// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_YQMlkHQLe7lJ3OTiAjFQ7fSFSe0Sp3M',
    appId: '1:1082500585109:web:24fd6716bc4d9a269ced9c',
    messagingSenderId: '1082500585109',
    projectId: 'facedetection-42aab',
    authDomain: 'facedetection-42aab.firebaseapp.com',
    storageBucket: 'facedetection-42aab.appspot.com',
    measurementId: 'G-4RBZEJM9KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIADTHqLmujM1i9NdNchFO12QXjYT0aRo',
    appId: '1:1082500585109:android:9bd955e88119dfbe9ced9c',
    messagingSenderId: '1082500585109',
    projectId: 'facedetection-42aab',
    storageBucket: 'facedetection-42aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArncJOcXOiso4zJr6nqmwxoGL7oMayxFQ',
    appId: '1:1082500585109:ios:adae20a639ca42809ced9c',
    messagingSenderId: '1082500585109',
    projectId: 'facedetection-42aab',
    storageBucket: 'facedetection-42aab.appspot.com',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArncJOcXOiso4zJr6nqmwxoGL7oMayxFQ',
    appId: '1:1082500585109:ios:adae20a639ca42809ced9c',
    messagingSenderId: '1082500585109',
    projectId: 'facedetection-42aab',
    storageBucket: 'facedetection-42aab.appspot.com',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_YQMlkHQLe7lJ3OTiAjFQ7fSFSe0Sp3M',
    appId: '1:1082500585109:web:d25755f2c9dccefc9ced9c',
    messagingSenderId: '1082500585109',
    projectId: 'facedetection-42aab',
    authDomain: 'facedetection-42aab.firebaseapp.com',
    storageBucket: 'facedetection-42aab.appspot.com',
    measurementId: 'G-D4WQJTKWQC',
  );
}
